debug: false

database:
  type: sqlite
  # sqlite的path
  path: plugins/UISystem/database.db
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  table: my_database
  #每10分钟同步一次 （tick）
  user-container-sync-time: 12000

resources:
  enable: true
  #加载的材质包名称，不需要带zip
  name: "UnrealResource"
  #材质包密码
  password: "123456"

#主动显示的js
Hud: []

disableHud:
#  - Health
#    Crosshair,
#    Armor,
#    Health,
#    Food,
#    Experiance,
#    HotBar,
#    Chat,
#    Air,
#    Scoreboard,
#    PlayerTab,
#    VehicleHealth,
#    JumpMeter;

