debug: false

resources:
  enable: true
  #加载的材质包名称，不需要带zip
  name: "UnrealResource"
  #材质包密码
  password: "123456"

#主动显示的js
Hud:
  - "TEST"


disableHud:
#  - Health
#    Crosshair,
#    Armor,
#    Health,
#    Food,
#    Experiance,
#    HotBar,
#    Chat,
#    Air,
#    Scoreboard,
#    PlayerTab,
#    VehicleHealth,
#    JumpMeter;

