const ModulesAPI = {
    Button: find("com.daxton.unrealcore.display.been.module.control.ButtonModuleData"),
    ChatDisplay: find("com.daxton.unrealcore.display.been.module.control.ChatDisplayModuleData"),
    CheckModuleData: find("com.daxton.unrealcore.display.been.module.control.CheckModuleData"),
    ContainerModule: find("com.daxton.unrealcore.display.been.module.control.ContainerModuleData"),
    ContainerModuleDataStaring: find("com.daxton.unrealcore.display.been.module.control.ContainerModuleDataStaring"),
    RangeModule: find("com.daxton.unrealcore.display.been.module.control.RangeModuleData"),
    SelectModule: find("com.daxton.unrealcore.display.been.module.control.SelectModuleData"),
    SlotModule: find("com.daxton.unrealcore.display.been.module.control.SlotModuleData"),
    EntityModule: find("com.daxton.unrealcore.display.been.module.display.EntityModuleData"),
    HotSlotModule: find("com.daxton.unrealcore.display.been.module.display.HotSlotModuleData"),
    ImageModuleData: find("com.daxton.unrealcore.display.been.module.display.ImageModuleData"),
    ItemModuleData: find("com.daxton.unrealcore.display.been.module.display.ItemModuleData"),
    ProgressModule: find("com.daxton.unrealcore.display.been.module.display.ProgressModuleData"),
    TextModule: find("com.daxton.unrealcore.display.been.module.display.TextModuleData"),
    AreaInputModule: find("com.daxton.unrealcore.display.been.module.input.AreaInputModuleData"),
    ChatInputModule: find("com.daxton.unrealcore.display.been.module.input.ChatInputModuleData"),
    InputModule: find("com.daxton.unrealcore.display.been.module.input.InputModuleData"),
    ModuleType: find("com.daxton.unrealcore.display.type.ModuleType")
}